server:
  port: 9000

spring:
  application:
    name: kuke-board-article-service
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/newVintly
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB116Dialect
    open-in-view: false


